name: CI Build Pipeline

on:
 push:
  branches: [ "**" ]
 workflow_dispatch:


jobs:
  build-backend:
      name: Build Backend Docker Image

      runs-on: ubuntu-latest

      steps:
        - name: Check out code
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push backend image
          uses: docker/build-push-action@v5
          with:
            context: .
            dockerfile: dockerfile
            push: ${{ github.ref == 'refs/heads/main' }}
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/tasks-manager-backend:latest
            
  build-frontend:
    name: Build Frontend Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: dockerfile.frontend
          push: ${{ github.ref == 'ref/heads/main' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/task-manager-frontend:latest
          

      